version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/apps/api_fastapi"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "devops-team"
    assignees:
      - "security-team"

  - package-ecosystem: "terraform"
    directory: "/infra/terraform/aws"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "devops-team"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5